services:
  backend:
    container_name: backend
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    build:
      context: ./projects/backend
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-production}
    volumes:
      - ./projects/backend/:/var/www/html/
      - ./projects/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV:-production}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: spectrum
      DB_USERNAME: spectrum_root
      DB_PASSWORD: spectrum_root
    networks:
      - app-network

  frontend:
    container_name: frontend
    restart: unless-stopped
    tty: true
    build:
      context: ./projects/frontend
      dockerfile: Dockerfile
    environment:
      PUBLIC_ENV__API_URL: http://nginx/api
    ports:
      - "3000:3000"
    volumes:
      - ./projects/frontend/:/app/
    networks:
      - app-network

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: spectrum_root
      MYSQL_DATABASE: spectrum
      MYSQL_USER: spectrum_root
      MYSQL_PASSWORD: spectrum_root
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./projects/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./projects/backend:/var/www/html
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge